# project name
spring.application.name=terralink

# connection url
spring.datasource.url=jdbc:mysql://localhost:3306/terralink_db

# access credentials
spring.datasource.username=root
spring.datasource.password=root

# official MySQL's Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# hibernate's settings
spring.jpa.hibernate.ddl-auto=update

# print mysql's queries
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true